import { useEffect, useState } from "react";

type Props = { onLogin: () => void; onSignup: () => void };
const features = [
  ["01", "Focus cycles", "Pick a length and a count. One dot per finished session—nothing else on screen."],
  ["02", "Flashcards", "Topics split into review groups with their own schedule and recall history."],
  ["03", "Notes", "Folders for thinking, with any note pinned as a floating sticky while you work."],
  ["04", "Countdowns", "Keep the date that matters visible in the corner of your workspace."],
  ["05", "Work log", "Every cycle recorded—completed or interrupted. An honest record, not a scoreboard."],
  ["06", "Stats", "Daily, weekly and monthly activity with streaks and targets you can inspect."],
];

export default function Landing({ onLogin, onSignup }: Props) {
  const [remaining, setRemaining] = useState(1500); const [playing, setPlaying] = useState(false); const [yearly, setYearly] = useState(false);
  useEffect(() => { if (!playing || !remaining) return; const id = setInterval(() => setRemaining(v => Math.max(0, v - 1)), 1000); return () => clearInterval(id); }, [playing, remaining]);
  const clock = `${String(Math.floor(remaining / 60)).padStart(2, "0")}:${String(remaining % 60).padStart(2, "0")}`;
  const theme = (value: string) => { document.documentElement.dataset.theme = value; localStorage.setItem("dot-theme", value); };
  return <main className="landing" id="top">
    <header className="landing-header"><a className="landing-brand" href="#top"><i />.DOT</a><nav><a href="#features">Features</a><a href="#how">How it works</a><a href="#pricing">Pricing</a></nav><div className="landing-actions"><span className="landing-theme"><button onClick={() => theme("light")}>Light</button><button onClick={() => theme("dark")}>Dark</button></span><button className="landing-link" onClick={onLogin}>Sign in</button><button className="landing-cta small" onClick={onSignup}>Start free</button></div></header>
    <section className="landing-hero"><span className="landing-kicker"><i />DEEP WORK, MADE VISIBLE</span><h1>One task. One timer.<br />One dot at a time.</h1><p>A calm place to protect your attention—focus cycles, flashcards, notes and countdowns in one quiet workspace that keeps the record for you.</p><div className="landing-hero-actions"><button className="landing-cta" onClick={onSignup}>Start focusing free</button><a className="landing-outline" href="#features">See how it works</a><span>No card. No streak guilt.</span></div>
      <div className="landing-demo"><div className="landing-windowbar"><i /><i /><i /><span>DOT — FOCUS CYCLE</span></div><div className="landing-demo-grid"><div><span className="landing-label">FOCUS TIME</span><strong className="landing-clock">{clock}</strong><div className="landing-progress"><i style={{ width: `${100 - remaining / 15}%` }} /></div><div className="landing-demo-actions"><button className="landing-cta small" onClick={() => setPlaying(v => !v)}>{playing ? "Pause" : "Start focus"}</button><button className="landing-outline small" onClick={() => { setPlaying(false); setRemaining(1500); }}>Reset</button></div><p>Try it—this timer is live.</p></div><div className="landing-today"><span className="landing-label">TODAY</span><div className="landing-dots">{[0,1,2,3,4,5].map(i => <i className={i < 3 ? "done" : ""} key={i} />)}</div><div className="landing-mini"><div><span>STREAK</span><strong>4 <small>days</small></strong></div><div><span>MINUTES</span><strong>1,265</strong></div></div><div className="landing-countdown"><b><i />Interview</b><span>3 DAYS · 08 HRS · 24 MIN</span></div></div></div></div>
      <div className="landing-proof">{[["31k+","focus cycles finished weekly"],["92%","finish the cycle they start"],["4.9","average rating, 1.2k reviews"],["0","ads, trackers, notifications"]].map(([v,k]) => <div key={k}><strong>{v}</strong><span>{k}</span></div>)}</div>
    </section>
    <section className="landing-section" id="features"><span className="landing-label">EVERYTHING, NOTHING MORE</span><h2>Six tools that respect your attention.</h2><div className="landing-feature-grid">{features.map(([n,title,body]) => <article key={n}><i>{n}</i><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="landing-section" id="how"><div className="landing-how"><div><span className="landing-label">HOW IT WORKS</span><h2>Three steps. Then silence.</h2>{[["01","Name the length","Twenty-five for a sprint, ninety for real depth."],["02","Start the cycle","Silence the rest and let the dots fill one at a time."],["03","Read the record","See what you actually did at the end of the week."]].map(([n,t,b]) => <article key={n}><i>{n}</i><span><b>{t}</b><small>{b}</small></span></article>)}</div><div className="landing-screen">PRODUCT SCREENSHOT<br /><small>stats view · 1400×980</small></div></div></section>
    <section className="landing-section" id="pricing"><div className="landing-pricing-head"><div><span className="landing-label">PRICING</span><h2>Pay for focus, not features.</h2></div><span className="landing-cycle"><button className={!yearly ? "active" : ""} onClick={() => setYearly(false)}>Monthly</button><button className={yearly ? "active" : ""} onClick={() => setYearly(true)}>Yearly · −20%</button></span></div><div className="landing-plans">{[["Quiet","0","One focus cycle a day, one topic, one folder."],["Focus",yearly ? "5" : "6","Unlimited cycles and the full record of your work."],["Studio",yearly ? "11" : "14","For pairs and small teams sharing a focus rhythm."]].map(([name,price,copy], i) => <article className={i === 1 ? "featured" : ""} key={name}><h3>{name}{i === 1 && <small>MOST PICKED</small>}</h3><strong>${price}</strong><span>{i ? "/month" : " forever"}</span><p>{copy}</p><button className={i === 1 ? "landing-cta" : "landing-outline"} onClick={onSignup}>{i === 1 ? "Start 14-day trial" : "Get started"}</button></article>)}</div></section>
    <section className="landing-signin"><div><span className="landing-label">START TODAY</span><h2>Your next hour can be the quiet one.</h2><p>Free forever for one focus cycle a day. Upgrade when the dots start adding up.</p></div><div><h3>Ready to focus?</h3><button className="landing-cta" onClick={onLogin}>Sign in</button><button className="landing-outline" onClick={onSignup}>Create an account</button></div></section>
    <footer className="landing-footer"><span className="landing-brand"><i />.DOT</span><span>© 2026 DOT LABS</span></footer>
  </main>;
}
